feat: add homework14
NatashaLaurie/TMSAndroidHomeworkNatashaL pull request #1
Opened 2021-12-04 19:03 UTC by NatashaLaurie

2021-12-04 19:57 UTC, zakharchanka requested changes

2021-12-04 19:57 UTC, zakharchanka commented on app/src/main/java/com/example/homework14/App1Activity.kt
> +            string.replace('а', 'о', true).also { string = it }
приятно видеть, что ты умеешь использовать also)

2021-12-04 19:57 UTC, zakharchanka commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
И этот файл можно добавить в .gitignore

2021-12-04 19:57 UTC, zakharchanka commented on .idea/misc.xml
>  <project version="4">
Этот файл можно добавить в .gitignore

2021-12-04 19:57 UTC, zakharchanka commented on app/src/main/java/com/example/homework14/App3Activity.kt
> +            "Два конца, два кольца,\n" +
Можно одинарные кавычки заменить на тройные """, тогда не нужно будет выставлять \n а просто печатать текст в том виде, в котором хочешь его вывести

2021-12-04 19:57 UTC, zakharchanka commented on app/src/main/java/com/example/homework14/App3Activity.kt
> +                } else makeToast("Не верно!").show()
Если у тебя if else длиннее, чем в одну строчку, я рекомендую ставить скобки {}. Без скобок в будущем можно допустить ошибки.

2021-12-04 19:57 UTC, zakharchanka commented on app/src/main/res/layout/activity_app4.xml
> +        android:onClick="onClick"
Я бы не рекомендовал вызывать клики напрямую из xml. Потом это тяжелее поддерживать и искать в коде.

2021-12-04 19:57 UTC, zakharchanka commented on app/src/main/AndroidManifest.xml
> +        android:fullBackupContent="true"
а для чего нужен этот атрибут?

2021-12-05 08:08 UTC, NatashaLaurie commented on app/src/main/java/com/example/homework14/App1Activity.kt
> +            string.replace('а', 'о', true).also { string = it }
:)

2021-12-05 08:19 UTC, NatashaLaurie commented on .idea/vcs.xml
> +<?xml version="1.0" encoding="UTF-8"?>
done

2021-12-05 08:19 UTC, NatashaLaurie commented on .idea/misc.xml
>  <project version="4">
done

2021-12-05 08:23 UTC, NatashaLaurie commented on app/src/main/java/com/example/homework14/App3Activity.kt
> +            "Два конца, два кольца,\n" +
done

2021-12-05 08:24 UTC, NatashaLaurie commented on app/src/main/java/com/example/homework14/App3Activity.kt
> +                } else makeToast("Не верно!").show()
done

2021-12-05 08:55 UTC, NatashaLaurie commented on app/src/main/AndroidManifest.xml
> +        android:fullBackupContent="true"
без него есть warning
On SDK version 23 and up, your app data will be automatically backed up and restored on app install. Consider adding the attribute `android:fullBackupContent` to specify an `@xml` resource which configures which files to backup, or just set `android:fullBackupOnly=true`. More info: https://developer.android.com/guide/topics/data/autobackup

2021-12-08 18:47 UTC, Sigezmund approved these changes

2021-12-08 18:47 UTC, merged